"""Reusable tokenizer training and runtime tokenization package.

Exports are resolved lazily to keep package import light for orchestration tests.
"""

from importlib import import_module

_EXPORT_MAP: dict[str, tuple[str, str]] = {
    "TokenizerArtifactPaths": (".paths", "TokenizerArtifactPaths"),
    "TokenizerDirectoryFiles": (".paths", "TokenizerDirectoryFiles"),
    "ScopeDirectoryFiles": (".paths", "ScopeDirectoryFiles"),
    "tokenizer_directory": (".paths", "tokenizer_directory"),
    "tokenizer_directory_files": (".paths", "tokenizer_directory_files"),
    "scope_directory_files": (".paths", "scope_directory_files"),
    "promoted_candidate_key": (".paths", "promoted_candidate_key"),
    "tokenizer_id": (".paths", "tokenizer_id"),
    "TOKENIZER_IDS": (".paths", "TOKENIZER_IDS"),
    "TokenizerFields": (".paths", "TokenizerFields"),
    "write_candidate_directory": (".paths", "write_candidate_directory"),
    "TRAINING_CORPUS_FILENAME": (".paths", "TRAINING_CORPUS_FILENAME"),
    "OptimizeCandidatePolicy": (".contracts", "OptimizeCandidatePolicy"),
    "OptimizeCandidateResult": (".contracts", "OptimizeCandidateResult"),
    "TrainingTarget": (".contracts", "TrainingTarget"),
    "candidate_key": (".optimize", "candidate_key"),
    "is_candidate_excluded": (".optimize", "is_candidate_excluded"),
    "scoped_history_for_trainer": (".optimize", "scoped_history_for_trainer"),
    "build_optimize_canary_payload": (".optimize", "build_optimize_canary_payload"),
    "build_optimize_summary_payload": (".optimize", "build_optimize_summary_payload"),
    "compute_optimize_grid_hash": (".optimize", "compute_optimize_grid_hash"),
    "resolve_country_tokenizer_paths": (".paths", "resolve_country_tokenizer_paths"),
    "resolve_global_tokenizer_paths": (".paths", "resolve_global_tokenizer_paths"),
    "resolve_tokenizer_paths": (".paths", "resolve_tokenizer_paths"),
    "to_portable_path_str": (".paths", "to_portable_path_str"),
    "SUPPORTED_TRAINERS": (".training", "SUPPORTED_TRAINERS"),
    "TrainerOptions": (".training", "TrainerOptions"),
    "estimate_wordpiece_vocab_size": (".training", "estimate_wordpiece_vocab_size"),
    "train_wordpiece": (".training", "train_wordpiece"),
    "train_sentencepiece": (".training", "train_sentencepiece"),
    "train_tokenizer_with_trainer": (".training", "train_tokenizer_with_trainer"),
    "load_tokenizer_encoder": (".training", "load_tokenizer_encoder"),
    "TokenizerVocabulary": (".vocabulary", "TokenizerVocabulary"),
    "load_tokenizer_vocabulary": (".vocabulary", "load_tokenizer_vocabulary"),
    "resolve_tokenizer_path_for_trainer": (
        ".training",
        "resolve_tokenizer_path_for_trainer",
    ),
    "resolve_metadata_path_for_trainer": (
        ".training",
        "resolve_metadata_path_for_trainer",
    ),
    "resolve_candidate_model_suffix_for_trainer": (
        ".training",
        "resolve_candidate_model_suffix_for_trainer",
    ),
    "compute_corpus_content_hash": (".training", "compute_corpus_content_hash"),
    "OptimizeSweepPaths": (".training", "OptimizeSweepPaths"),
    "resolve_optimize_dir": (".training", "resolve_optimize_dir"),
    "resolve_optimize_sweep_paths": (".training", "resolve_optimize_sweep_paths"),
    "resolve_active_optimize_sweep_dir": (
        ".training",
        "resolve_active_optimize_sweep_dir",
    ),
    "resolve_optimize_splits_dir": (".training", "resolve_optimize_splits_dir"),
    "resolve_optimize_canary_pointer_path": (
        ".training",
        "resolve_optimize_canary_pointer_path",
    ),
    "validate_trainer_options": (".training", "validate_trainer_options"),
    "normalize_optimize_min_frequencies_for_trainer": (
        ".training",
        "normalize_optimize_min_frequencies_for_trainer",
    ),
    "trainer_params_payload": (".training", "trainer_params_payload"),
    "RUN_MANIFEST_MANDATORY_FIELDS": (
        ".manifest",
        "RUN_MANIFEST_MANDATORY_FIELDS",
    ),
    "RUN_MANIFEST_OPTIONAL_FIELDS": (".manifest", "RUN_MANIFEST_OPTIONAL_FIELDS"),
    "RUN_MANIFEST_MODES": (".manifest", "RUN_MANIFEST_MODES"),
    "build_run_manifest": (".manifest", "build_run_manifest"),
    "validate_run_manifest": (".manifest", "validate_run_manifest"),
    "DUAL_TOKENIZER_ROLES": (".manifest", "DUAL_TOKENIZER_ROLES"),
    "validate_dual_tokenizer_coherence": (
        ".manifest",
        "validate_dual_tokenizer_coherence",
    ),
    "load_run_manifest_if_present": (".manifest", "load_run_manifest_if_present"),
    "validate_dual_tokenizer_artifacts": (
        ".manifest",
        "validate_dual_tokenizer_artifacts",
    ),
    "TokenizationRequest": (".tokenization_params", "TokenizationRequest"),
    "TokenizerCalculationSpec": (".tokenization_params", "TokenizerCalculationSpec"),
    "compile_tokenization_request": (
        ".tokenization_params",
        "compile_tokenization_request",
    ),
    "coerce_tokenization_request": (
        ".tokenization_params",
        "coerce_tokenization_request",
    ),
    "TokenizeFilesRequest": (".ops", "TokenizeFilesRequest"),
    "tokenize_name": (".ops", "tokenize_name"),
    "tokenize_name_with_request": (".ops", "tokenize_name_with_request"),
    "tokenize_name_dual": (".ops", "tokenize_name_dual"),
    "tokenize_name_multi": (".ops", "tokenize_name_multi"),
    "tokenize_name_dataframe": (".tokenization", "tokenize_name_dataframe"),
    "tokenize_name_dataframe_with_request": (
        ".tokenization",
        "tokenize_name_dataframe_with_request",
    ),
    "tokenize_name_dataframe_dual": (".tokenization", "tokenize_name_dataframe_dual"),
    "tokenize_name_dataframe_multi": (".tokenization", "tokenize_name_dataframe_multi"),
    "compute_corpus_token_tfidf_stats": (".tfidf", "compute_corpus_token_tfidf_stats"),
    "compute_tokenizer_token_tfidf_stats": (
        ".tfidf",
        "compute_tokenizer_token_tfidf_stats",
    ),
    "normalize_tfidf_use_case": (".tfidf", "normalize_tfidf_use_case"),
    "expected_tfidf_namespace": (".tfidf", "expected_tfidf_namespace"),
    "validate_tfidf_namespace": (".tfidf", "validate_tfidf_namespace"),
    "resolve_noise_words": (".tfidf", "resolve_noise_words"),
    "cumulative_document_frequency_mass_cutoff": (
        ".tfidf",
        "cumulative_document_frequency_mass_cutoff",
    ),
    "count_tokens_above_document_frequency_pct": (
        ".tfidf",
        "count_tokens_above_document_frequency_pct",
    ),
    "select_stopword_candidates": (".tfidf", "select_stopword_candidates"),
    "select_rare_token_candidates": (".tfidf", "select_rare_token_candidates"),
    "trim_name_before_tokenization": (".tfidf", "trim_name_before_tokenization"),
    "trim_token_column": (".tfidf", "trim_token_column"),
    "SUPPORTED_POOLING_RULES": (".tfidf", "SUPPORTED_POOLING_RULES"),
    "normalize_pooling_rule": (".tfidf", "normalize_pooling_rule"),
    "infer_document_count_from_tfidf_stats": (
        ".tfidf",
        "infer_document_count_from_tfidf_stats",
    ),
    "pool_token_tfidf_stats": (".tfidf", "pool_token_tfidf_stats"),
    "trim_pooled_corpus_by_system": (".tfidf", "trim_pooled_corpus_by_system"),
    "DEFAULT_MAX_NOISE_WORD_CANDIDATES": (
        ".noise_export",
        "DEFAULT_MAX_NOISE_WORD_CANDIDATES",
    ),
    "select_noise_word_candidates": (
        ".noise_export",
        "select_noise_word_candidates",
    ),
    "build_noise_word_candidates_payload": (
        ".noise_export",
        "build_noise_word_candidates_payload",
    ),
    "validate_noise_word_candidates_payload": (
        ".noise_export",
        "validate_noise_word_candidates_payload",
    ),
    "summarize_noise_word_candidates": (
        ".noise_export",
        "summarize_noise_word_candidates",
    ),
    "resolve_candidate_model_path": (
        ".candidate_archive",
        "resolve_candidate_model_path",
    ),
    "resolve_archive_dir": (".candidate_archive", "resolve_archive_dir"),
    "read_archive_index": (".candidate_archive", "read_archive_index"),
    "write_archive_index": (".candidate_archive", "write_archive_index"),
    "attach_report_to_archive_entry": (
        ".candidate_archive",
        "attach_report_to_archive_entry",
    ),
    "archive_optimize_candidate": (".candidate_archive", "archive_optimize_candidate"),
    "archive_naive_tokenizer": (".candidate_archive", "archive_naive_tokenizer"),
    "archive_trained_tokenizer": (".candidate_archive", "archive_trained_tokenizer"),
    "archive_promoted_tokenizer": (".candidate_archive", "archive_promoted_tokenizer"),
    "compare_archive_entries": (".candidate_archive", "compare_archive_entries"),
    "resolve_archive_label": (".candidate_archive", "resolve_archive_label"),
    "ArchivedTokenizerSelection": (
        ".candidate_archive",
        "ArchivedTokenizerSelection",
    ),
    "resolve_archived_tokenizer_path": (
        ".candidate_archive",
        "resolve_archived_tokenizer_path",
    ),
}


def __getattr__(name: str):
    target = _EXPORT_MAP.get(name)
    if target is None:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
    module_name, attr_name = target
    module = import_module(module_name, package=__name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


__all__ = [
    "TokenizerArtifactPaths",
    "TokenizerDirectoryFiles",
    "ScopeDirectoryFiles",
    "tokenizer_directory",
    "tokenizer_directory_files",
    "scope_directory_files",
    "promoted_candidate_key",
    "tokenizer_id",
    "TOKENIZER_IDS",
    "TokenizerFields",
    "write_candidate_directory",
    "TRAINING_CORPUS_FILENAME",
    "OptimizeCandidatePolicy",
    "OptimizeCandidateResult",
    "TrainingTarget",
    "candidate_key",
    "is_candidate_excluded",
    "scoped_history_for_trainer",
    "build_optimize_canary_payload",
    "build_optimize_summary_payload",
    "compute_optimize_grid_hash",
    "resolve_country_tokenizer_paths",
    "resolve_global_tokenizer_paths",
    "resolve_tokenizer_paths",
    "to_portable_path_str",
    "SUPPORTED_TRAINERS",
    "TrainerOptions",
    "estimate_wordpiece_vocab_size",
    "train_wordpiece",
    "train_sentencepiece",
    "train_tokenizer_with_trainer",
    "load_tokenizer_encoder",
    "TokenizerVocabulary",
    "load_tokenizer_vocabulary",
    "resolve_tokenizer_path_for_trainer",
    "resolve_metadata_path_for_trainer",
    "resolve_candidate_model_suffix_for_trainer",
    "compute_corpus_content_hash",
    "OptimizeSweepPaths",
    "resolve_optimize_dir",
    "resolve_optimize_sweep_paths",
    "resolve_active_optimize_sweep_dir",
    "resolve_optimize_splits_dir",
    "resolve_optimize_canary_pointer_path",
    "validate_trainer_options",
    "normalize_optimize_min_frequencies_for_trainer",
    "trainer_params_payload",
    "RUN_MANIFEST_MANDATORY_FIELDS",
    "RUN_MANIFEST_OPTIONAL_FIELDS",
    "RUN_MANIFEST_MODES",
    "build_run_manifest",
    "validate_run_manifest",
    "DUAL_TOKENIZER_ROLES",
    "validate_dual_tokenizer_coherence",
    "load_run_manifest_if_present",
    "validate_dual_tokenizer_artifacts",
    "TokenizationRequest",
    "TokenizerCalculationSpec",
    "compile_tokenization_request",
    "coerce_tokenization_request",
    "TokenizeFilesRequest",
    "tokenize_name",
    "tokenize_name_with_request",
    "tokenize_name_dual",
    "tokenize_name_multi",
    "tokenize_name_dataframe",
    "tokenize_name_dataframe_with_request",
    "tokenize_name_dataframe_dual",
    "tokenize_name_dataframe_multi",
    "compute_corpus_token_tfidf_stats",
    "compute_tokenizer_token_tfidf_stats",
    "normalize_tfidf_use_case",
    "expected_tfidf_namespace",
    "validate_tfidf_namespace",
    "resolve_noise_words",
    "cumulative_document_frequency_mass_cutoff",
    "count_tokens_above_document_frequency_pct",
    "select_stopword_candidates",
    "select_rare_token_candidates",
    "trim_name_before_tokenization",
    "trim_token_column",
    "SUPPORTED_POOLING_RULES",
    "normalize_pooling_rule",
    "infer_document_count_from_tfidf_stats",
    "pool_token_tfidf_stats",
    "trim_pooled_corpus_by_system",
    "DEFAULT_MAX_NOISE_WORD_CANDIDATES",
    "select_noise_word_candidates",
    "build_noise_word_candidates_payload",
    "validate_noise_word_candidates_payload",
    "summarize_noise_word_candidates",
    "resolve_candidate_model_path",
    "resolve_archive_dir",
    "read_archive_index",
    "write_archive_index",
    "attach_report_to_archive_entry",
    "archive_optimize_candidate",
    "archive_naive_tokenizer",
    "archive_trained_tokenizer",
    "archive_promoted_tokenizer",
    "compare_archive_entries",
    "resolve_archive_label",
    "ArchivedTokenizerSelection",
    "resolve_archived_tokenizer_path",
]
