from __future__ import annotations

# System plan statuses and supported-country selectors live in `constants_status`.

# Access modes
ACCESS_MODE_BULK_DOWNLOAD = "bulk_download"
ACCESS_MODE_API_OPEN = "api_open"
ACCESS_MODE_API_CONTRACT = "api_contract"
ACCESS_MODE_SEARCH_PORTAL = "search_portal"

ALLOWED_ACCESS_MODES = frozenset(
    {
        ACCESS_MODE_BULK_DOWNLOAD,
        ACCESS_MODE_API_OPEN,
        ACCESS_MODE_API_CONTRACT,
        ACCESS_MODE_SEARCH_PORTAL,
    }
)

# Research priorities
RESEARCH_PRIORITY_P1 = "P1"
RESEARCH_PRIORITY_P2 = "P2"
RESEARCH_PRIORITY_P3 = "P3"
RESEARCH_PRIORITY_P4 = "P4"
RESEARCH_PRIORITY_P5 = "P5"

DEFAULT_RESEARCH_PRIORITY = RESEARCH_PRIORITY_P5

ALLOWED_RESEARCH_PRIORITIES = frozenset(
    {
        RESEARCH_PRIORITY_P1,
        RESEARCH_PRIORITY_P2,
        RESEARCH_PRIORITY_P3,
        RESEARCH_PRIORITY_P4,
        RESEARCH_PRIORITY_P5,
    }
)

PROCESS_STAGE_ACQUIRE = "acquire"
PROCESS_STAGE_SHARD = "shard"
PROCESS_STAGE_CANONICAL = "canonical"
PROCESS_STAGE_CLEANSE = "cleanse"
PROCESS_STAGE_MATCH = "match"
PROCESS_STAGE_TOKENIZE = "tokenize"

PIPELINE_STAGE_NAMES = (
    PROCESS_STAGE_ACQUIRE,
    PROCESS_STAGE_SHARD,
    PROCESS_STAGE_CANONICAL,
    PROCESS_STAGE_CLEANSE,
    PROCESS_STAGE_MATCH,
    PROCESS_STAGE_TOKENIZE,
)
DEFAULT_PROCESS_STAGES = PIPELINE_STAGE_NAMES[1:]
OPTIONAL_PROCESS_STAGES = PIPELINE_STAGE_NAMES[:1]
ALLOWED_PROCESS_STAGES = frozenset(PIPELINE_STAGE_NAMES)
