"""Write the diagram palette and fonts from docs/diagrams/house-style.css into the files
the PlantUML and Structurizr toolchains include, since neither reads CSS.

* ``docs/plantuml/_palette.puml``     - ``!$accent = "#1F5FAD"`` and so on, used by ``_style.puml``.
* ``docs/structurizr/_palette.dsl``   - ``!const ACCENT "#1F5FAD"`` and so on, used by ``views.dsl``.

Both are generated: edit house-style.css, never them. Only the light values are written,
since both toolchains render one fixed light theme. ``export_diagrams.py`` runs this before
every export, so a render never uses a stale palette.

Usage::

    python tooling/sync_palette.py
"""

from __future__ import annotations

import re
from pathlib import Path

from _tooling_common import repository_root

REPO_ROOT = repository_root(Path(__file__))
HOUSE_STYLE = REPO_ROOT / "docs" / "diagrams" / "house-style.css"
PUML_PALETTE = REPO_ROOT / "docs" / "plantuml" / "_palette.puml"
DSL_PALETTE = REPO_ROOT / "docs" / "structurizr" / "_palette.dsl"

# The first :root block is the light theme; the dark sets follow it in the file.
LIGHT_ROOT_RE = re.compile(r":root\s*\{([^{}]*)\}")
TOKEN_RE = re.compile(r"--([\w-]+)\s*:\s*([^;]+);")
FIRST_FAMILY_RE = re.compile(r"""^\s*['"]?([^'",]+)""")

# PlantUML and the Structurizr renderer pick fonts installed on the machine, not web fonts,
# so each family gets a fallback a stock machine has.
FONT_FALLBACKS = {
    "font-display": "Verdana, sans-serif",
    "font-body": "Verdana, sans-serif",
    "font-mono": "Consolas, monospace",
}

HEADER = "generated by tooling/sync_palette.py from docs/diagrams/house-style.css; edit that file, not this one"


def read_tokens() -> dict[str, str]:
    """The light theme's colour tokens, and each font token as a PlantUML font list."""
    root = LIGHT_ROOT_RE.search(HOUSE_STYLE.read_text(encoding="utf-8"))
    if not root:
        raise SystemExit(f"No :root block in {HOUSE_STYLE}")
    tokens: dict[str, str] = {}
    for name, value in TOKEN_RE.findall(root.group(1)):
        value = value.strip()
        if name in FONT_FALLBACKS:
            family = FIRST_FAMILY_RE.match(value)
            if not family:
                raise SystemExit(f"--{name} names no font in {HOUSE_STYLE}")
            tokens[name] = f"{family.group(1).strip()}, {FONT_FALLBACKS[name]}"
        elif value.startswith("#"):
            tokens[name] = value
    return tokens


def render_puml(tokens: dict[str, str]) -> str:
    lines = [f"/' {HEADER} '/"]
    lines += [f'!${name.replace("-", "_")} = "{value}"' for name, value in tokens.items()]
    return "\n".join(lines) + "\n"


def render_dsl(tokens: dict[str, str]) -> str:
    lines = [f"// {HEADER}"]
    lines += [f'!const {name.replace("-", "_").upper()} "{value}"' for name, value in tokens.items()]
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def sync_palette() -> list[Path]:
    """Regenerate both palette files; returns the ones whose content changed."""
    tokens = read_tokens()
    written = [
        path
        for path, text in ((PUML_PALETTE, render_puml(tokens)), (DSL_PALETTE, render_dsl(tokens)))
        if write_if_changed(path, text)
    ]
    return written


def main() -> int:
    for path in sync_palette():
        print(f"  palette -> {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
